# Generated by Django 4.2.6 on 2023-11-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodelform',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
