# Generated by Django 4.2.6 on 2023-11-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_bookmodelform_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModelForm',
            new_name='Book',
        ),
    ]
