# Generated by Django 4.2.6 on 2023-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
