# Generated by Django 4.2.6 on 2023-11-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
